TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

ARCHIVE = archive.archive
ARCHIVE += sioc-sys0-ml00.archive sioc-sys0-ml01.archive sioc-sys0-ml02.archive sioc-sys0-ml03.archive
ARCHIVE += sioc-sys1-ml00.archive sioc-sys1-ml01.archive sioc-sys1-ml02.archive sioc-sys1-ml03.archive
ARCHIVE += sioc-sys2-ml00.archive sioc-sys2-ml01.archive sioc-sys2-ml02.archive sioc-sys2-ml03.archive
ARCHIVE += sioc-sys6-ml00.archive sioc-sys6-ml01.archive sioc-sys6-ml02.archive sioc-sys6-ml03.archive
ARCHIVE += sioc-sys7-ml00.archive sioc-sys7-ml01.archive sioc-sys7-ml02.archive sioc-sys7-ml03.archive
ARCHIVE += sioc-sys8-ml00.archive sioc-sys8-ml01.archive sioc-sys8-ml02.archive sioc-sys8-ml03.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

